apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s/name: objects-api
    app: flask
    role: api
  name: objects-api
  namespace: tierchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s/name: objects-api
      app: flask
  template:
    metadata:
      labels:
        k8s/name: objects-api
        app: flask
    spec:
      containers:
      - image: gclntm/objects_api:v1.0.0
        name: api
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: aws_default_region
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: objects-api
  labels:
    app: flask
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: objects-api
  selector:
    app: flask
    k8s/name: objects-api
  type: LoadBalancer
  externalIPs:
  - {{EXTERNAL_IP}}
